### PR TITLE
Input overlapping new button fix

### PR DESCRIPTION
**Pull request by YaroslavOvdii**
@tonytlwu @squallstar 
## Issue
https://github.com/Fliplet/fliplet-studio/issues/4655

## Description
Changed the min-width value of the input. Witch is worked for Edge 12-17 browser only, Edge 18 worked fine with the previous solution.
Also changed select width for a better input view.
## Screenshots/screencasts
issue input overlapps

## Backward compatibility

This change is fully backward compatible.

## Notes
For the Edge 12-17, we need to add a polyfill to use .finally in Promise. As it was done for IE11.
Because of that the spinner-overlay isn't cloaking himself

### CODE REVIEW

**Comment by tonytlwu** [comment]
@YaroslavOvdii Our Promise polyfill has `.finally()` implemented already. Is this sufficient? https://github.com/Fliplet/fliplet-api/blob/02c4509801ecb77aaea7291446c4a05bfb2f0fdc/public/assets/fliplet-runtime/1.0/vendor/promise.js#L142-L157

Also, can we think of another solution that doesn't need the button to be specifically styled as `120px`? This leaves an exposure for error in the future -- most developers won't think of having to update a button width via CSS if they change the button label.

**Comment by YaroslavOvdii** [comment]
@tonytlwu 
In MS Edge version 17.17134 and earlier this polyfill isn't working. Showing console error witch says, finally is not a function.
In Internet Explorer 11 polyfill works fine.
Unfortunately, I can't show you the screenshot now because my browser was updated to the 18 version last Friday and I can't roll back to the previous version.

Maybe it will be better not to change the width at all for Edge? 
It should look like this
image
Will it be okay?

**Comment by tonytlwu** [comment]
@YaroslavOvdii No, that doesn't look good. I'd suggest not using `.finally()` until it works reliably.

**Comment by YaroslavOvdii** [comment]
image
@tonytlwu 
Fixed.

**Pull request merged**
