### PR TITLE
Correct files and folders order

### PR DESCRIPTION
**Pull request by manst**
When files are uploaded to a folder they should be inserted in the correct order instead of at the end
correct order = in alphabetical order Ascending
The sorting is not case sensitive
1. Folders A-Z
2. Files A-Z

ref [Fliplet/fliplet-studio#240](https://github.com/Fliplet/fliplet-studio/issues/240)

### CODE REVIEW

**Comment by squallstar** [comment]
@manst any chance we can sort the data prior to rendering instead of having to check the DOM every time we append one element?

**Comment by manst** [comment]
@squallstar  Yes, but in this case, we should rerender all list if we add one element (e.g. create a folder), or keep separate logic to add one element to a specific place and other to render all list.

**Comment by squallstar** [comment]
I understand, however adding a file/folder is less common than rendering a list hence I would suggest to optimise the reading rather than the updating.

@tonytlwu do you agree?

**Comment by manst** [comment]
We can keep this logic for add one element and add new logic for rendering all list on open a folder

**Comment by squallstar** [comment]
I'm not a fan of doubling logic if I must be honest, because it makes the code less DRY and harder to maintain. 

I don't think re-rendering a list when a new file gets uploaded will be a bottleneck.

**Comment by squallstar** [comment]
@manst if the logic can be reused, feel free to write code that is able to both sort the items in first place and then insert items at the right index. e.g.:

```
sortItems(items) {
  // return the new sorted items
}
renderItem(item) {
  // render a single item
}
renderItems(items) {
  // render all the items, could reuse renderItem
}
findItemInsertPoint(item) {
  // return the point of insertion
}
insertItem(item) {
  // Uses findItemInsertPoint() and renderItem()
}
```

@tonytlwu thanks for the snippet above.

**Comment by manst** [comment]
Hi @squallstar, I have updated code

**Comment by squallstar** [comment]
@manst great! I've forwarded this to @tonytlwu to double check and approve too.

**Comment by squallstar** [comment]
@manst this PR has conflicts (they came in after we merged the "search" PR)

**Comment by manst** [comment]
@squallstar conflict resolved

**Pull request merged**
